### ISSUE TITLE
Part 4: TfLite-Micro code out of date

### ISSUE THREAD

**Issue by EnzoBuscaglia** [ShawnHymel/tinyml-example-anomaly-detection#2]
Hi. Thanks for the amazing job you've put throughout this repository.
After implementing and testing every code in all 4 parts of this experience I got stuck at the end of it, particularly testing the esp32_test_tflite.ino file. Apparently, Tensorflow Lite-Micro's Github repository has undergone several changes since the release of this series, so your code can no longer run correctly.
The first error is related to the fact that the ESP32s don't have peripherals, so I had to comment out line  #include "peripherals/peripherals.h" from TensorFlowLite.h header file. 
The second errors are easy to fix and are related to the relocation of the files imported in lines 11-16 of your code (just remove "experimental" from path). But after it, a new error came from lines 81-85 (Compilation error: 'Register_FULLY_CONNECTED' is not a member of 'tflite::ops::micro'). I replaced those lines with just "micro_mutable_op_resolver.AddFullyConnected();" and added "<1>" to the MicroMutableOpResolver object, but again I got a new error so I stopped trying to the debug the code (Compilation error: no matching function for call to 'tflite::MicroInterpreter::MicroInterpreter(const tflite::Model*&, tflite::MicroMutableOpResolver<1>&, uint8_t [1024], const int&, tflite::ErrorReporter*&)').
Would it be possible for you to update your code so it could work properly with the current state of TfLite-Micro's Github repository ?
Thanks a lot!

**Comment by ShawnHymel** [comment]
Hi EnzoBuscaglia,

I'm glad the repo has been helpful! Unfortunately, I do not have the time to keep all of my examples and demos up to date with the ever-changing TensorFlow libraries :( I recommend either using an earlier version of TF or making the changes you mentioned. Pull requests are also welcome if you do get something working.

**Comment by EnzoBuscaglia** [comment]
Thanks for your answer. In case anyone gets stuck with the same problem, I found the proper TfLite-Micro version in the comments in this post from the Arduino forum:
https://forum.arduino.cc/t/why-i-cant-find-the-arduino-tensorflowlite-library-in-library-management/1044070/9
